apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
type: Opaque
data:
  # "vocalyx_dev_password" base64
  DB_PASSWORD: dm9jYWx5eF9kZXZfcGFzc3dvcmQ=
  # "root" base64
  DB_USERNAME: cm9vdA==
  # your JWT secret base64 — encode it:
  # [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("hYw0Jr6z8cP6a6p7H1K8v0h2V9r3Q5t8Y2l7s3D6e9w="))
  JWT_SECRET: aFl3MEpyNno4Y1A2YTZwN0gxSzh2MGgyVjlyM1E1dDhZMmw3czNENmU5dz0=
  # your gmail address base64
  MAIL_USERNAME: c2Fsb25oYWlydGFnQGdtYWlsLmNvbQ==
  # your gmail app password base64
  MAIL_PASSWORD: ZmV0ZyB6c2FjIHFmcXogcmR3ZQ==