apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  # These are base64 encoded values
  # "vocalyx_dev_password" → base64
  root-password: dm9jYWx5eF9kZXZfcGFzc3dvcmQ=
  database: dm9jYWx5eA==