grafana:
  adminPassword: "vocalyx-admin"

  service:
    type: NodePort
    nodePort: 30030

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      isDefault: false

prometheus:
  prometheusSpec:
    retention: 7d

    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false

    additionalScrapeConfigs:
      - job_name: kubernetes-pods-annotations
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            regex: "true"
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
            target_label: __metrics_path__
            regex: (.+)
          - action: replace
            source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod

    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "300m"

alertmanager:
  enabled: false

nodeExporter:
  enabled: true